@startuml
'https://plantuml.com/class-diagram

hide empty members

entity users {
+id: int [PK]
--
username: string
}

entity todo_applications {
# id: int [PK][FK(user,id)]
--
# type_id: int [FK(todo_application_type,id)]
application_user_id: int
access_token: string
sync_status: json
first_synced_at: datetime
last_synced_at: datetime
}

entity todo_application_types {
+ id: int
--
name: string
}

entity todos {
+id: int [PK]
--
#todo_application_id: int [FK(todo_application,id)]
uuid: int
name: string
raw_data: json
project_name: string
origin_created_at: datetime
}

entity todo_plans {
todo_id: int [FK(todo,id)]
status_id:
plan: string
due: datetime
}

entity todo_done_datetimes {
+id: int [PK]
--
#todo_id: int [FK(todo,id)]
done_datetime: datetime
}

entity routine_watcher_settings {
# id: int [PK][FK(user,id)]
--
project_id: int
tag_ids: json
due_filter: boolean
}

entity notifiers {
+ id: int [PK]
--
# user_id: int[FK(user,id)]
# type_id: int[FK(notifier_type,id)]
condition: json
}

entity notifier_types {
+ id: int [PK]
--
name: string
}

users -- todo_applications
users - routine_watcher_settings
users -left-o{ notifiers
notifiers }o-- notifier_types

todo_applications }o- todo_application_types
todo_applications --o{ todos
todos --o{ todo_done_datetimes
todos -o{ todo_plans

@enduml
