@startuml
'https://plantuml.com/class-diagram

hide empty members

entity user {
+id: int [PK]
--
username: string
}

entity todo_application {
# id: int [PK][FK(user,id)]
--
# type_id: int [FK(todo_application_type,id)]
application_user_id: int
access_token: string
sync_status: json
first_synced_at: datetime
last_synced_at: datetime
}

entity todo_application_type {
+ id: int
--
name: string
}

entity todo {
+id: int [PK]
--
#todo_application_id: int [FK(todo_application,id)]
uuid: int
name: string
raw_data: json
project_name: string
origin_created_at: datetime
}

entity todo_plans {
todo_id: int [FK(todo,id)]
status_id:
plan: string
due: datetime
}

entity done_datetime {
+id: int [PK]
--
#todo_id: int [FK(todo,id)]
done_datetime: datetime
}

entity routine_watcher_setting {
# id: int [PK][FK(user,id)]
--
project_id: int
tag_ids: json
due_filter: boolean
}

entity notifier {
+ id: int [PK]
--
# user_id: int[FK(user,id)]
# type_id: int[FK(notifier_type,id)]
condition: json
}

entity notifier_type {
+ id: int [PK]
--
name: string
}

user -- todo_application
user - routine_watcher_setting
user -left-o{ notifier
notifier }o-- notifier_type

todo_application }o- todo_application_type
todo_application --o{ todo
todo --o{ done_datetime
todo -o{ todo_plans

@enduml
